### ISSUE TITLE
Can't run tutorial

### ISSUE THREAD

**Issue by EmaPK** [scipr-lab/libsnark#39]
I am trying to run the tutorial by running `g++ src/gadgetlib2/examples/tutorial.hpp
` from the libsnark folder without success. I am working on Ubuntu 15, with g++-5.2.

The error is: `tutorial.cpp:14:33: fatal error: gadgetlib2/gadget.hpp: No such file or directory.`

If I change the line to a path relative to the cpp file e.g. `#include "../gadget.hpp"` then that error is fixed, but it starts to show the same error in a chain in the next file it finds `pp.hpp:13:42: fatal error: common/default_types/ec_pp.hpp: No such file or directory`

What am I doing wrong?

**Comment by imolfar** [comment]
Same here.
@EmaPK you can get `ec_pp.hpp` here https://github.com/ebfull/hackishlibsnarkbindings/tree/master/libsnark/src/common/default_types
Though it's just beginning, there's lot more missing files : )
Also for relative path just add `-Isrc` flag.

**Comment by dcmiddle** [comment]
I believe this PR will resolve the build issue within the current cmake approach.
https://github.com/scipr-lab/libsnark/pull/105
